"""One judge for six manifests — the contract behind C1–C12, and the kit pin.

WHY. `tests/test_qa_conformance.py` was a TEMPLATE copied into six repos, and it
checked that a manifest was HONEST (paths exist, ● has evidence, ◐/○ has a
reason) — never what ● MEANS. So "C7 implemented" was a different claim in each
repo and nothing forced the meanings to converge. `contract.yml` is the meaning;
this module holds every manifest to it. The consumer test becomes a thin
delegate, because a judge with six copies drifts and one cannot.

Two strengths of finding, on purpose:

  FATAL     the manifest lies — a check missing, ● without evidence, an evidence
            path that does not exist, ◐/○ without a reason, a status outside the
            three, a name that is not the check's.
  ADVISORY  ● without `ran:` (claimed, not shown), ◐ whose `missing:` names no
            key from the contract's `partial_may_lack`. These print as `●?` and
            `◐?` in the matrix and do not fail the suite until the repo turns
            them on — the estate's adoption rule.

THE PIN. A register generated by an older kit answers a different question
while looking identical. `pin_agrees` asserts, without a kit checkout: the
manifest's `bench.version` equals the INSTALLED kit's version; every tracked
file that names a `qa-bench@` ref names the installed kit's COMMIT; and there is
exactly one such ref. IGA's version of this test resolved the pinned commit
through `~/Projects/qa-bench` — 30 commits behind — and had been SKIPPING for a
week with the suite green.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

import yaml

CONTRACT = Path(__file__).with_name("contract.yml")
MARK = {"implemented": "●", "partial": "◐", "absent": "○"}
FATAL_KINDS = {"missing", "status", "name", "evidence_missing", "no_evidence", "no_reason"}

#: Manifest fields this kit must NEVER execute, with the reason — asserted, not
#: merely absent from a run list. `full_remote` dispatches the night lane, and on
#: at least one project that lane PROMOTES TO PRODUCTION ON GREEN: a future
#: widening that reads it as "a cheap one-line command field" would turn a
#: conformance run into a production deploy. Any code that runs a manifest field
#: consults this set first.
NEVER_RUN = {
    "full_remote": "dispatches the night lane, which on tharros promotes to production on green",
    "full_local": "is the whole night lane on a laptop — the most expensive thing a project owns",
    "unit_tier": "is a test tier; tiers are verdicted by `ran` when they actually run",
    "browser_tier": "is a test tier; tiers are verdicted by `ran` when they actually run",
}
#: Manifest fields that are cheap and read-only, and so may be demanded to run.
RUN_TO_VERIFY = ("enumerate_routes",)


def contract() -> dict:
    return yaml.safe_load(CONTRACT.read_text(encoding="utf-8"))


def _finding(check: str, kind: str, text: str) -> dict:
    return {"check": check, "kind": kind, "fatal": kind in FATAL_KINDS, "text": text}


def judge(manifest: dict, root: Path | None = None) -> list[dict]:
    """Every way `manifest` falls short of the contract. Empty means clean.

    `root` makes evidence paths checkable; without it, existence is not judged
    (the consumer test passes it; a report reading a manifest off GitHub cannot).
    """
    c = contract()
    checks = manifest.get("checks")
    out: list[dict] = []
    if not isinstance(checks, dict):
        return [_finding("*", "missing", "manifest has no `checks:` block")]
    for cid, rule in c["checks"].items():
        spec = checks.get(cid)
        if not isinstance(spec, dict):
            out.append(_finding(cid, "missing", f"{cid} is not in the manifest — a hole in the matrix, not a blank"))
            continue
        status = spec.get("status")
        if status not in c["statuses"]:
            out.append(_finding(cid, "status", f"{cid}: status {status!r} is not one of {c['statuses']}"))
            continue
        if spec.get("name") != rule["name"]:
            out.append(_finding(cid, "name", f"{cid} is named {spec.get('name')!r}; the contract calls it {rule['name']!r}"))
        evidence = spec.get("evidence")
        if not isinstance(evidence, list):
            out.append(_finding(cid, "no_evidence", f"{cid}: evidence must be a list (may be empty)"))
            evidence = []
        if root is not None:
            for rel in evidence:
                if not (Path(root) / rel).exists():
                    out.append(_finding(cid, "evidence_missing", f"{cid}: evidence {rel!r} does not exist — a cell that lies"))
        if status == "implemented":
            if not evidence:
                out.append(_finding(cid, "no_evidence", f"{cid}: implemented with no evidence is a claim, not a status"))
            if not str(spec.get("ran") or "").strip():
                out.append(_finding(cid, "unproven", f"{cid}: implemented, but nothing named proves it RAN — contract asks for: {rule['ran_proof']}"))
        else:
            if not str(spec.get("reason") or "").strip():
                out.append(_finding(cid, "no_reason", f"{cid}: {status} needs a reason — what is missing, in one sentence"))
            if status == "partial":
                missing = spec.get("missing")
                allowed = set(rule["partial_may_lack"])
                named = [m for m in (missing or []) if m in allowed] if isinstance(missing, list) else []
                if not named:
                    out.append(_finding(cid, "partial_unnamed",
                                        f"{cid}: partial must name what is missing with `missing: [...]` from {sorted(allowed)}"))
                elif isinstance(missing, list) and set(missing) - allowed:
                    out.append(_finding(cid, "partial_unnamed",
                                        f"{cid}: `missing` names {sorted(set(missing) - allowed)}, which the contract does not know; use {sorted(allowed)}"))
    # ANY COMMAND A DOCUMENT HANDS YOU IS UNTESTED UNLESS SOMETHING RUNS IT.
    # tharros's `enumerate_routes` printed 4 routes out of 216 under its pinned
    # framework, with no error, while the project's own code walked the router
    # correctly: the manifest held a stale copy and nothing executed it. A
    # presence check on the KEY is the only thing that was checking it. So a
    # manifest declaring an enumeration command must register it as a
    # `population` guard — run, compared by member against a second derivation,
    # and holding at least one named witness. Advisory first, per the estate's
    # adoption rule; it becomes fatal per repo once that repo is clean.
    command = str(manifest.get("enumerate_routes") or "").strip()
    if command and root is not None:
        reg = (manifest.get("population") or {}).get("register")
        guards = []
        if reg and (Path(root) / reg).exists():
            guards = (yaml.safe_load((Path(root) / reg).read_text(encoding="utf-8")) or {}).get("guards") or []
        reads_it = [g for g in guards if isinstance(g, dict)
                    and (g.get("population") or {}).get("cmd_from") == "enumerate_routes"]
        copies_it = [g for g in guards if isinstance(g, dict)
                     and str(((g.get("population") or {}).get("cmd") or "")).strip() == command]
        runs_it = reads_it or copies_it
        if copies_it and not reads_it:
            out.append(_finding("C10", "enumeration_copied",
                                "a population guard runs a PASTED COPY of enumerate_routes rather than reading it with "
                                "`cmd_from: enumerate_routes` — the copy passes today and drifts the next time the "
                                "manifest line changes, which is the same defect one file over: the copy runs, and "
                                "is no longer the command anybody consumes"))
        if not runs_it:
            out.append(_finding("C10", "enumeration_unrun",
                                "enumerate_routes is declared and NOTHING RUNS IT — any command a document hands you "
                                "is untested unless something runs it. tharros's printed 4 routes of 216 with no "
                                "error while its own code walked the router correctly. Register it as a population "
                                "guard with a second-derivation superset and a named witness"))
        elif not any((g.get("population") or {}).get("witness") for g in runs_it):
            out.append(_finding("C10", "enumeration_unwitnessed",
                                "enumerate_routes runs as a population guard with no named witness — a near-empty "
                                "result reads as a small, clean project, and only a named route can see that"))
    # WHAT DOES LANDING CAUSE? On tharros a merge to main — documented as "the
    # day lane to staging" — is also a PRODUCTION RELEASE that night: a 22:00
    # LaunchAgent dispatches qa-nightly, which on green dispatches the
    # production deploy for main's SHA. Found by reading the workflow, not from
    # any document that says "merging schedules production". The act that looks
    # like staging is the act that schedules production. So a manifest with a
    # promotion lane names the chain a routine event starts, as FILES the judge
    # can check exist — a free-text sentence here would be one more warrant
    # nobody verifies.
    if str(manifest.get("full_remote") or "").strip():
        landing = manifest.get("landing")
        if not isinstance(landing, dict) or not landing.get("chain"):
            out.append(_finding("C7", "landing_unmapped",
                                "this project has a promotion lane and does not say what LANDING CAUSES. On tharros a "
                                "merge to main, documented as the day lane to staging, is also a production release "
                                "that night — found by reading the workflow, not from any doc. Declare `landing: "
                                "{event, chain: [workflow files], reaches_production}` so it is written down and "
                                "checked rather than rediscovered"))
        elif root is not None:
            gone = [f for f in landing["chain"] if not (Path(root) / str(f)).exists()]
            if gone:
                out.append(_finding("C7", "landing_chain_missing",
                                    f"`landing.chain` names files that do not exist: {', '.join(map(str, gone))} — a "
                                    "map of what landing causes that points at nothing is the stale copy again"))
    extra = sorted(set(checks) - set(c["checks"]))
    if extra:
        out.append(_finding("*", "missing", f"checks beyond the twelve: {extra} — a thirteenth needs three ledger rows that fit none of the twelve"))
    return out


def fatal(findings: list[dict]) -> list[dict]:
    return [f for f in findings if f["fatal"]]


def matrix(manifest: dict, findings: list[dict], project: str = "") -> str:
    """The adoption matrix with the advisory marks: ●? claimed-not-shown, ◐? unnamed."""
    c = contract()
    checks = manifest.get("checks") or {}
    advisory = {(f["check"], f["kind"]) for f in findings if not f["fatal"]}
    rows = [f"{project or manifest.get('project', '')} — QA adoption matrix", ""]
    counts = {"implemented": 0, "partial": 0, "absent": 0, "unproven": 0, "unnamed": 0}
    for cid, rule in c["checks"].items():
        spec = checks.get(cid) or {}
        status = spec.get("status")
        mark = MARK.get(status, "?")
        if (cid, "unproven") in advisory:
            mark += "?"
            counts["unproven"] += 1
        elif (cid, "partial_unnamed") in advisory:
            mark += "?"
            counts["unnamed"] += 1
        if status in counts:
            counts[status] += 1
        rows.append(f"  {mark:<3} {cid:<4} {rule['name']:<30} {len(spec.get('evidence') or [])} file(s)"
                    + (f"  ran: {spec['ran']}" if spec.get("ran") else ""))
        if status == "partial" and spec.get("missing"):
            rows.append(f"            missing: {', '.join(map(str, spec['missing']))}")
        if status != "implemented" and spec.get("reason"):
            rows.append(f"            {str(spec['reason']).strip().splitlines()[0][:110]}")
    rows += ["", f"  ● {counts['implemented']}  ◐ {counts['partial']}  ○ {counts['absent']}"
             f"   ●? {counts['unproven']} claimed without ran-proof   ◐? {counts['unnamed']} partial without a named gap"]
    return "\n".join(rows)


# --- the pin ------------------------------------------------------------------

def installed_kit() -> tuple[str | None, str | None]:
    """(version, commit) of the qabench this interpreter runs, from its own
    metadata — no checkout, no network. commit is None when it was not installed
    from git (an editable checkout, say)."""
    from importlib.metadata import PackageNotFoundError, distribution
    try:
        dist = distribution("qabench")
    except PackageNotFoundError:
        return None, None
    commit = None
    raw = dist.read_text("direct_url.json")
    if raw:
        try:
            commit = (json.loads(raw).get("vcs_info") or {}).get("commit_id")
        except json.JSONDecodeError:
            commit = None
    return dist.version, commit


#: An install of the kit that names NO ref. `pin_refs` cannot see it — its
#: regex needs the `@` — which is how anat's shared-bench.yml ran `pip install
#: --upgrade "qabench @ git+…/qa-bench"` on the runner that holds staging's
#: secrets while every pin guard in the repo stayed green.
_UNPINNED = re.compile(r"""git\+[a-z]+://[^\s"']*/qa-bench(?:\.git)?(?=["'\s]|$)""")


def unpinned_installs(root, *, ignore=()) -> list[tuple[str, str]]:
    """[(tracked file, the line)] for every kit URL that carries no `@ref`."""
    import subprocess
    root = Path(root)
    files = subprocess.run(["git", "ls-files"], cwd=root, capture_output=True, text=True).stdout.split("\n")
    found = []
    for rel in files:
        if not rel or rel in ignore:
            continue
        try:
            text = (root / rel).read_text(encoding="utf-8", errors="replace")
        except (OSError, IsADirectoryError):
            continue
        for line in text.splitlines():
            if _UNPINNED.search(line) and not line.lstrip().startswith("#"):
                found.append((rel, line))
    return found


def pin_agrees(root, *, ignore=(), installed: tuple[str | None, str | None] | None = None) -> list[str]:
    """Every way the repo's kit pins disagree with each other or with what runs.
    Empty means one kit, one commit, and the manifest names it."""
    from .gestures import pin_refs
    root = Path(root)
    version, commit = installed if installed is not None else installed_kit()
    out: list[str] = []
    manifest_path = root / "qa" / "manifest.yml"
    pinned = None
    if manifest_path.exists():
        doc = yaml.safe_load(manifest_path.read_text(encoding="utf-8")) or {}
        pinned = (doc.get("bench") or {}).get("version")
    if pinned is None:
        out.append("qa/manifest.yml names no bench.version — the registers here were made by a kit nobody can name")
    elif version is None:
        out.append("qabench is not installed in this interpreter — the pin cannot be compared with anything")
    elif str(pinned) != str(version):
        out.append(f"qa/manifest.yml pins bench.version {pinned} but the installed kit is {version} — "
                   "`python -m qabench` refuses the night on exactly this; move both in one commit")
    for rel, line in unpinned_installs(root, ignore=ignore):
        out.append(f"{rel}: installs the kit with no ref at all ({line.strip()[:80]}) — CI runs whatever is on main that day")
    refs = pin_refs(root, ignore=ignore)
    if not refs:
        out.append("no tracked file names a qa-bench ref — CI installs whatever is on main, or this read nothing; treat as DID NOT RUN")
    if len(refs) > 1:
        out.append("more than one qa-bench ref in this repo: " + "; ".join(
            f"{ref} in {', '.join(files)}" for ref, files in sorted(refs.items())))
    for ref, files in sorted(refs.items()):
        if not re.fullmatch(r"[0-9a-f]{40}", ref):
            out.append(f"{ref} ({', '.join(files)}) is not a full commit — a tag or branch can move under the pin")
        elif commit and ref != commit:
            out.append(f"{', '.join(files)} pin {ref[:8]} but the installed kit is {commit[:8]} — this interpreter is not running what CI will")
    return out
